---
title: "Cleaning Weekly Data"
output:  html_document
---

```{r message=FALSE}
#Libraries
#detach(package:plyr) ### Run once.. Important to get the weighted average to work. 
library(tidyr)
library(lubridate)
library(dplyr)
library(readr)
library(magrittr)
library(stats)
library(rio)
library(ggplot2)
library(plotly)
library(data.table)
library(ggthemes)


```

#Functions
```{r}

#Function imports various dataframes into the global environment given a list with the file names, the file extension, the path to the files, and the naming convention for the imported data frames. 

importf <- function(alist, extension, apath, dfname){
  dfList <- lapply(alist, function(x){
    return(read_csv(paste(apath, x, extension, sep = "")))
  })
  for (i in seq(dfList))
  assign(paste("w",i, dfname, sep = ""), dfList[[i]], envir=.GlobalEnv)
}


#Applying lapply and then saving the output dfs back to the global environment Applies a function to each data frame in a list of data frames, and saves them to the global environment. 

lapply_and_save <- function(a_df_list, a_function, optional_argument1, optional_argument2, optional_argument3, a_name) {
  if(missing(optional_argument1) & missing(optional_argument2) & missing(optional_argument3)) {
    temp_df <- lapply(a_df_list, a_function)
    for (i in seq(temp_df))
    assign(paste("w",i, a_name, sep = ""), temp_df[[i]], envir=.GlobalEnv)
  }
  else if(missing(optional_argument2) & missing(optional_argument3)){
    temp_df <- lapply(a_df_list, a_function, optional_argument1)
    for (i in seq(temp_df))
    assign(paste("w",i, a_name, sep = ""), temp_df[[i]], envir=.GlobalEnv)
  }
  
  else if(missing(optional_argument3)){
    temp_df <- lapply(a_df_list, a_function, optional_argument1, optional_argument2)
    for (i in seq(temp_df))
    assign(paste("w",i, a_name, sep = ""), temp_df[[i]], envir=.GlobalEnv)
  }
  else {
        temp_df <- lapply(a_df_list, a_function, optional_argument1,
                          optional_argument2, optional_argument3) 
        for (i in seq(temp_df))
          assign(paste("w",i, a_name, sep = ""), temp_df[[i]], envir=.GlobalEnv)
    }}


#Replaces a value (by default -3) throughout a dataframe with another value (by default NA). 

recodef <- function(df, replace_value = -3, replace_with = NA) {
        x <- df
        x[x == replace_value] <- replace_with
        #return(x)
        assign(deparse(substitute(df)), x, envir=.GlobalEnv)}


#Replaces a value (by default -3) throughout a dataframe with another value (by default NA). 

renamecolf <- function(df, from, to) {
        x <- df
        names(x)[names(x) == from] <- to
        #return(x)
        assign(deparse(substitute(df)), x, envir=.GlobalEnv)}

#Given year and month in two separate columns, creates a field called date that is in the format year, month, day with the day being the first day of the month (01)

create_date_field <- function(df){
  x <- df
  x <- unite(x, "date", c(`year`, `mo`), sep = "-")
  x["date"] <- apply(x[,c("date")],2, function(each){paste0(each, '-01')})
  x$date <- as.Date(x$date)
  assign(deparse(substitute(df)), x, envir=.GlobalEnv)
}

#Find Water year from date field, given water year starting month. 

get_water_date <- function(df, water_year_start = 153){
  x <- df
  x %<>%
    mutate(water_date = date - days(water_year_start - 1))
  assign(deparse(substitute(df)), x, envir=.GlobalEnv)}

#Create Year Date
create_water_year_date <- function(df, water_year_start = 06){
  x <- df
  x %<>%
    mutate(water_year_date = water_date) %>%
    separate(water_year_date, c("water_year"), sep = "-")
  x["water_year"] <- apply(x[,c("water_year")],2, function(x){paste0(x,'-', as.character(water_year_start), '-01')})
  x$water_year <- as.Date(x$water_year)
  assign(deparse(substitute(df)), x, envir=.GlobalEnv)
  }

#Get H concentration from pH

get_Hydrogen <- function(df){
  x <- df
  x %<>% 
    mutate(H = 10^(-pH)*1000)
  #return(x)
  assign(deparse(substitute(df)), x, envir=.GlobalEnv)}


#Gather function that creates solute and concentration_mg columns. It understands all columns that have a capital letter as elements and puts them under the solute column. It takes their corresponding values and puts them under the concentration_mg column. 
gather_concentration <- function(df){
  x <- df
  x <- gather(x, solute, concentration_mg_week, matches("[A-Z]", ignore.case = FALSE))
  x$concentration_mg_week <- as.numeric(x$concentration_mg_week)
  assign(deparse(substitute(df)), x, envir=.GlobalEnv)
}


#Gather function that creates water source and water_mm_month (water in mm per month) columns. It understands columns that have a either precip or streamflow as showing water sources and puts them under the source column. It takes their corresponding values and puts them under the water_mm_month column. 

gather_source <- function(df){
  x <- df
  x <- gather(x, source, water_mm_week, matches("precipitation|streamflow", ignore.case = FALSE))
  x$water_mm_week <- as.numeric(x$water_mm_week)
  assign(deparse(substitute(df)), x, envir=.GlobalEnv)
}


#Function that filters by watershed and then finds the difference in each variable between Q and P (P-Q). 

get_differencef<- function(df, wsfilter, granularityfilter){
df %>% 
  filter(ws == wsfilter)%>% 
  filter(granularity == granularityfilter)%>% 
  group_by(ws, water_year, water_date, granularity, solute) %>%
  arrange(desc(source)) %>%
  summarise_each(funs(diff), concentration_mg, concentration_ueq,concentration_umol,flux)}


# precip_streamflow_weekly_data_long %>%
#   filter(ws == "1")%>%
#   filter(granularity == "week")%>%
#   group_by(ws, water_year, water_date, granularity, solute) %>%
#   arrange(desc(source)) %>%
#   summarise(n=n())


```


#Import All Data

```{r message=FALSE}

#Import Data

streamflow_weekly <- read_csv("data_original/HBEF_stream_chemistry_1963-2013.csv")
precipitation_weekly <- read_csv("data_original/HBEF_precipitation_chemistry_1963-2013.csv")


load("public_data.Rdata", envir = parent.frame(), verbose = FALSE)

#change charge for Al from NA to 3
MW.data[4, "z"] <- 3

#change charge for NH4 from NA to 1
MW.data[5, "z"] <- 1

#change charge for PO4 from NA to -3
MW.data[11, "z"] <- -3

#change charge for HCO3 from NA to -3
newrow <- data.frame("solute" = "HCO3", "MW" = 61.0168, "z"= -1, stringsAsFactors=FALSE)
MW.data <- rbind(MW.data, newrow)


```


#Clean Data

```{r}



#remove columns that will not be used yet. 
precipitation_weekly %<>% 
  select(-X1, -sp.cond, -note)


streamflow_weekly %<>% 
  select(-X1, -sp.cond, -temp, -hydro.limb, -note, -ANC, -DIC)


#Change colnames to streamflow and precipitation --> this is important because we are trying to unify names. 
#rename columns
renamecolf(streamflow_weekly, "Q", "streamflow")
renamecolf(precipitation_weekly, "precip", "precipitation")

#renamecolf(streamflow_weekly, "ANC", "anc")
renamecolf(precipitation_weekly, "site", "ws")

precipitation_weekly$ws <- recodef(precipitation_weekly$ws, "S", 1)
precipitation_weekly$ws <- recodef(precipitation_weekly$ws, "N", 7)

#eliminate duplicates
streamflow_weekly <- streamflow_weekly[!duplicated(streamflow_weekly[,c("ws", "date")]),]
precipitation_weekly <- precipitation_weekly[!duplicated(precipitation_weekly[,c("ws", "date")]),]

```



#Working with dates

```{r message = FALSE}
#Create water date field

get_water_date(streamflow_weekly, 152)
get_water_date(precipitation_weekly, 152)

create_water_year_date(streamflow_weekly, water_year_start = 06)
create_water_year_date(precipitation_weekly, water_year_start = 06)

```


#Getting pH

```{r}
#Get H from pH

get_Hydrogen(streamflow_weekly)
get_Hydrogen(precipitation_weekly)


```


#Gathering

```{r}
#Gather Solutes and Concentration_mg

gather_concentration(streamflow_weekly)
gather_concentration(precipitation_weekly)

#Gather Water source so that there's a column for water source (either precip or streamflow) and one for 

gather_source(streamflow_weekly)
gather_source(precipitation_weekly)


```



```{r}

#Concatenate both precip and streamflow weekly.   

precip_streamflow_weekly_data_long <- plyr::rbind.fill(precipitation_weekly, streamflow_weekly)

#Join new complete df with molecular weight data (MW.data) to calculate mol and eq values. 

precip_streamflow_weekly_data_long<- left_join(precip_streamflow_weekly_data_long, MW.data, by = "solute")


# Calculate ueq, umol, and flux. 
precip_streamflow_weekly_data_long %<>% 
  mutate(concentration_ueq_week =
          ifelse(is.na(precip_streamflow_weekly_data_long$MW), NA,
                 (((concentration_mg_week/1000)/MW)*(abs(z))*10^6))) %>%
  mutate(concentration_umol_week = 
           ifelse(is.na(precip_streamflow_weekly_data_long$MW), NA,
                  (((concentration_mg_week/1000)/MW))*10^6)) %>% 
  mutate(flux_week = 
           ifelse(is.na(precip_streamflow_weekly_data_long$MW), NA,
                  (((concentration_mg_week/1000)/MW)*(abs(z))*water_mm_week*10000)))

```



#Enlongate df. 

After creating the new variables that find yearly data from month data, we are going to elongate the df so that granularity is a column that specifies if value is for year or month. 

```{r}

#Gather for it to be long and then extract the granularity (month or year) from the column value

precip_streamflow_weekly_data_long <- precip_streamflow_weekly_data_long %>%
  gather(key, value, concentration_mg_week, water_mm_week, concentration_ueq_week,
         concentration_umol_week, flux_week) %>%
  tidyr::extract(key, c('unit', 'granularity'), "(.*)_(.*)") %>% 
  spread(unit, value)

```


#Duplicate so each ws has a row

```{r}

for(x in seq(2,6)){
  nam <- paste("precip_ws_",x, sep = "")
  df <- precip_streamflow_weekly_data_long %>%
  filter(source == "precipitation") %>% 
  filter(ws =="1")
  df[,"ws"] <- x 
  assign(nam, df)}


for(x in seq(8,9)){
  nam <- paste("precip_ws_",x, sep = "")
  df <- precip_streamflow_weekly_data_long %>%
  filter(source == "precipitation") %>% 
  filter(ws =="7")
  df[,"ws"] <- x 
  assign(nam, df)}

precip_streamflow_weekly_data_long <- do.call("rbind", list(precip_ws_2, precip_ws_3, precip_ws_4, precip_ws_5, precip_ws_6,precip_ws_8, precip_ws_9,precip_streamflow_weekly_data_long))

```



#Export data to precip_stream_data .Rdata

```{r}

#Export File

save(precip_streamflow_weekly_data_long, file = "precip_streamflow_weekly_data_long.Rdata")

```


#Wide df

```{r}

long <- precip_streamflow_weekly_data_long
drop <- c("z", "MW")
df <- long[, !(names(long) %in% drop)]
fixed <- c("ws","date","water_date", "datetime", "water_year","canonical", "source", "water_mm", "granularity", "solute", "datetime", "canonical")
values <- colnames(df[, !(names(df) %in% fixed)])

precip_streamflow_weekly_data_wide <- data.table::dcast(data.table::setDT(df), ws + date + water_date + datetime + water_year + source + water_mm + granularity + canonical ~ solute, value.var = values)

precip_streamflow_weekly_data_wide$ws <- as.factor(precip_streamflow_weekly_data_wide$ws)
precip_streamflow_weekly_data_wide$source <- as.factor(precip_streamflow_weekly_data_wide$source)


#add column with just year to be able to animate by frames

precip_streamflow_weekly_data_wide$frame <- precip_streamflow_weekly_data_wide$water_date
precip_streamflow_weekly_data_wide %<>% 
  separate("frame", c("framey") )

save(precip_streamflow_weekly_data_wide, file = "precip_streamflow_weekly_data_wide.Rdata")



```



```{r}

rm(list=ls())

load("precip_streamflow_weekly_data_long.RData")
load("precip_streamflow_weekly_data_wide.RData")

save(list = ls(all.names = TRUE), file = "precip_streamflow_weekly_dfs.RData", envir = .GlobalEnv)

```

